### ISSUE TITLE
JPA class drag n drop Reverse Engineering support

### ISSUE THREAD

**Issue by jGauravGupta** [jeddict/jeddict#133]
Developer can drop the entity class file in modeler to reverse engineer java class in existing modeler file.

Ref : org.netbeans.modeler.actions.CustomAcceptProvider
transferable.isDataFlavorSupported(DataFlavor.javaFileListFlavor);
List<File> files = (List<File>) t.getTransferData(DataFlavor.javaFileListFlavor);

**Comment by Mobidat** [comment]
This would be a very nice feature!

**Comment by jGauravGupta** [comment]
Duplicate Issue : #195

**Comment by sgomanf** [comment]
if I have entities created in a library with the jpa class diagram (another jar file) and I want to reference them from another jpamodeler (eg web project). How would it be done?

**Comment by jGauravGupta** [comment]
Hi @sgomanf ,

Currently cross-project entity reverse engineering is not supported. Once drag-n-drop feature for entity reverse engineering will be available, it will supported.

**Comment by sgomanf** [comment]
Thanks for answering jGauravGupta.
Actually I did not mean to perform reverse engineering, but to reference entities of another diagram that recite in another project. For example, create a library of entities that are commonly used (project A), and from another (project B) inherit or relate to them. Then from the diagram of project B take the entities you want from the diagram of project A and make the relationships you want. When generating the source code of the project B diagram, the entities taken from project A would not be generated, since the latter were generated in project A. The entities taken from the diagram of project A can not be modified in the diagram of project B, only referenced. All handled at the level of diagrams not with reverse engineering of classes.
