### ISSUE TITLE
Implement the DB visualizer into the service window for create DB and create Table

### ISSUE THREAD

**Issue by Chris2011** [jeddict/jeddict#17]
It would be very nice and handy, if we can have a create DB/Table via the JPA modeler when I right click on the MySQL node on the service window and say "create DB" I set a name and after this, the JPA modeler should comes up that I can create Tables via the JPA modeler. I think atm it is not possible.

The other thing is to visualize the existing Tables to see the relations and everything like in the very nice DB designer of the MS SQL Server Management Studio. And when I say create table, I should get an option to see the JPA Modeler or the code.

Regards

Chris

**Comment by Chris2011** [comment]
Like this: http://www.yaldex.com/sql_server_tutorial_3/images/01lss01_alt.jpg

**Comment by Chris2011** [comment]
I didn't checked it out but any news here? What is meaned with future release?.

**Comment by jGauravGupta** [comment]
Hi @Chris2011 , 

It will be great enhancement to  NetBeans > Services > Databases. It will have two component : 
 - Visualize the existing database
 - Create/Modify the database

The second point have major effort to ensure database portability. And in exiting DB Modeler (in JPA Modeler) , it is using persistence provider logic. so that's why existing  DB Modeler is db independent.

Future release means it is not planned for any upcoming release due to major effort and less priority than the planned task but it is good point so opened for future release planning.

**Comment by Chris2011** [comment]
Sounds awesome. Thx :)

**Comment by Chris2011** [comment]
Any news here? Less priority maybe? Or bigger problems?

**Comment by jGauravGupta** [comment]
Blocker :  Currently many user reported slowness issue for existing modeler. In case of Native DB modeler, of-course developer usually try to open their big production schema.

High Priority : This feature is really great and missing in NetBeans, see here : https://twitter.com/pierobonanno/status/866197941790416896

**Comment by Chris2011** [comment]
The blocker I understand, but which feature do you mean?

**Comment by jGauravGupta** [comment]
DB visualizer into the service window

**Comment by Chris2011** [comment]
ahh ok.

**Comment by Chris2011** [comment]
Because from the tweet I couldn't figure out what you meant. It was only a discussion which IDE is better and whether you can do a plugin for IntelliJ or not :D thats why Im asking.

**Comment by jGauravGupta** [comment]
Currently Native DB viewer is available. 
NetBeans internal API have issue with the rename table functionality so DB editor is not done yet.
