### ISSUE TITLE
Collaboration with easyUML

### ISSUE THREAD

**Issue by Chris2011** [jeddict/jeddict#24]
I know that JPA nothing had todo with UML before, but why not? I mean, you create classes with it and associations so It would be cool, if JPAModeler could be the next UML thing OR core functionality can move to easyUML too. EasyUML is rarely not developed as fast as your plugin. So with this knowledge, it would be great to help the guys or whatever. What do you think?

**Comment by jGauravGupta** [comment]
Hi Chris,

Priority of JPA Modeler feature is decided based on the number of client usage(market trends) and how efficiently it makes Java EE developer life easy.

Feature like DB Visualizer(standalone) , UML are already exist in market but definitely it will help, if these features are provided by JPA Modeler(have major development cost).

But there are too many features are pending, like complete Java EE 8 application generator that will cover Angularjs, Security, Elastic Search, Cache(Redis etc), Netflix etc etc etc.....and much more(means Java EE developer have to just focus on business logic and development environment will be ready based on the selected features)

You may share the more information/doc/ref about how this UML feature going to help more in compare to current diagram.

So that it will be prioritize in such a way.

**Comment by jGauravGupta** [comment]
I have seen easyuml, It is really good (but not much intuitive) and helpful in educational purpose instead-of JPA Modeler is more about productivity with design document . 
In future JPA Modeler will provide the support to UML in some extent (not 100% uml support) with JAVA domain Class , Interface and their association. 

ENUM support will not be available(less priority) because it requires many change by developer itself instead of just modeling.

**Comment by Chris2011** [comment]
Are any news here?

**Comment by jGauravGupta** [comment]
Here is the current development status :
JSONB modeler (in development) > DTO modeler > partial UML support

**Comment by Chris2011** [comment]
Great. Thx.
