### ISSUE TITLE
plugins missing from Persistence

### ISSUE THREAD

**Issue by jmls** [jeddict/jeddict#245]
I'm trying to use netbeans and jeddict for the first time - followed all the installation instructions and all seemed to be fine.

I wanted to import an existing db, but the tutorials show a load more options in the Persistence file type than I do

![image](https://user-images.githubusercontent.com/929523/30737047-1921cf22-9f7d-11e7-875c-ac32401bf0a2.png)

![image](https://user-images.githubusercontent.com/929523/30737069-24daa690-9f7d-11e7-86e7-9aeca29ab03a.png)

All the plugins seem to be installed and working

![image](https://user-images.githubusercontent.com/929523/30737112-4ba7ba4c-9f7d-11e7-82e7-a3c4b31131ff.png)

so I'm now stuck and not sure what to do next ;)

**Comment by jmls** [comment]
mmm, ok, if I create a `Java` project then all the files are there ..

**Comment by Mobidat** [comment]
I think with this path : https://github.com/jeddict/uc/releases/download/8.2.P2/updates.xml - installed in plugins/settings menu - you get the old 4.4.1 version. I have the same problem.

**Comment by jGauravGupta** [comment]
@jmls => Yes, you need to create Maven Web Project for full stack application generation and Java Project only supports JPA entity generation.

@Mobidat => Due to recent major release (Java EE 8 support), It is not available on  8.2.P2 update center. Because it will automatically update the latest plugin in your ide even in the case you want to stick with Java EE 7.

Soon after the release of NetBeans 9, new update center url will be available for NB9 with Java EE 8 support.
