### ISSUE TITLE
@JoinColumns annotation not generated

### ISSUE THREAD

**Issue by imerljak** [jeddict/jeddict#268]
##### **`@JoinColumns` annotation is not being generated when creating JPA models**

When generating JPA models from database diagram the `@JoinColumns` annotation is not being generated when needed, instead it annotates the relationship with multiple `@JoinColumn` (which is correct, but it needs to be wrapped by a `@JoinColumns`  at least until JPA 2.1). 

##### **Expected Outcome**

![captura de tela de 2018-04-12 10-09-40](https://user-images.githubusercontent.com/17605203/38679252-aef88f30-3e39-11e8-8010-8b1d20c72a70.png)

##### **Current Outcome**

![captura de tela de 2018-04-12 10-09-00](https://user-images.githubusercontent.com/17605203/38679263-b3809926-3e39-11e8-9796-607913aa7d81.png)

##### **Steps to Reproduce**(Only for bug reports) 
I'm working with a legacy database (with over 500 tables), i have generated the diagram from the database schema using the JPA Diagram from Database(Import DB) option. And just created the JPA models, haven't changed anything except adding a Serializable interface (i've run it twice, first without interface and the error persisted on both runs), and cofiguring the destination package. 

*PS: If needed, i could attach the generated diagram here.*

##### **Jeddict Version(s)**
4.8

**Comment by jGauravGupta** [comment]
Hi @imerljak,

The JPA 2.2 is a maintenance release and Repeatable annotation is one of the change to adapt the Java 8 features.

![image](https://user-images.githubusercontent.com/15934072/38680328-acde29c2-3e83-11e8-9852-535f5f9bc88d.png)

This is the JPA 2.1 snippet, as you can see here JoinColumn annotation is wrapped with JoinColumns annotation because before Java 8, you were not allowed to annotate class/method/attribute with multiple instances of same annotation, that’s why JPA 2.1 used container annotation like JoinColumns.

You can change the Java version using NetBeans > Project > Properties > Source
In case, you have to use older Java version then please download the older version Jeddict which supports only Java EE 7 : https://jeddict.github.io/page.html?l=p/download

For more info about new Java EE 8 features : 
https://www.slideshare.net/jGauravGupta/rapid-development-tools-for-java-ee-8-tut2998

**Comment by imerljak** [comment]
Thank you for answering to promptly!
I will see how i can proceed about the Java version then.
